// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a4bhUrqWbeGH9fzcN7EwNU
import * as React from "react";
import { ChakraProvider } from "@chakra-ui/react"; // plasmic-import: FlI9iG1YAgn/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  chakraProviderProps?: Partial<
    Omit<React.ComponentProps<typeof ChakraProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, chakraProviderProps } = props;

  return (
    <ChakraProvider
      {...chakraProviderProps}
      theme={
        chakraProviderProps && "theme" in chakraProviderProps
          ? chakraProviderProps.theme!
          : undefined
      }
    >
      {children}
    </ChakraProvider>
  );
}
